<!DOCTYPE html>
<html lang="ar" dir="rtl">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <style>
        body { font-family: 'DejaVu Sans', sans-serif; direction: rtl; text-align: right; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #000; padding-bottom: 10px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #000; padding: 8px; text-align: center; }
        th { background-color: #f2f2f2; }
        .footer { margin-top: 30px; text-align: left; font-style: italic; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Gold Transactions Report</h1>
        <p>Generation Date: {{ now()->format('Y-m-d H:i') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>customer name</th>
                <th>ID Number/Iqama</th>
                <th>phone number</th>
                <th>type</th>
                <th>karat</th>
                <th>weight</th>
                <th>total sale price</th>
                {{-- <th>product image</th> --}}
                <th>staff name</th>
            </tr>
        </thead>
        <tbody>
            @foreach($transactions as $item)
            <tr>
                <td>{{ $item->created_at->format('Y-m-d') }}</td>
                <td>{{ $item->customer_name }}</td>
                <td>{{ $item->id_number }}</td>
                <td>{{ $item->phone }}</td>
                <td>{{ $item->type == 'sale' ? 'Sale' : 'Purchase' }}</td>
                <td>{{ $item->karat }}</td>
                <td>{{ $item->weight }} g</td>
                <td>{{ number_format($item->sale_price, 2) }} SR</td>
                {{-- <td>
                    @if($item->product_image)
                        <img src="{{ public_path('storage/' . $item->product_image) }}" alt="Product Image" width="50">
                    @else
                        N/A
                    @endif
                </td> --}}
                <td>{{ $item->staff_name }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Total Transactions of sales: {{ $transactions->where('type', 'sale')->count()  }}</p>
        <p>Total Sales Amount: {{ number_format($transactions->where('type', 'sale')->sum('sale_price'), 2) }} SR</p>
        ________________________________________________________________________________________________
        <p>Total Transactions of purchases: {{ $transactions->where('type', 'purchase')->count() }}</p>
        <p>Total Purchase Amount: {{ number_format($transactions->where('type', 'purchase')->sum('sale_price'), 2) }} SR</p>
        ________________________________________________________________________________________________
        <p>total net profit: {{ number_format($transactions->where('type', 'sale')->sum('sale_price') - $transactions->where('type', 'purchase')->sum('sale_price'), 2) }} SR</p>
        <p>that pdf file was generated by the Gold Management System - {{ auth()->user()->name }}</p>
    </div>
</body>
</html>